# Generated by Django 3.2.8 on 2024-10-21 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('cedula', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('celular', models.CharField(max_length=15)),
                ('sueldo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_ingreso', models.DateField()),
                ('cargo', models.CharField(max_length=100)),
                ('eps', models.CharField(max_length=100)),
                ('pension', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Desprendible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horas_extra_diurna', models.IntegerField(default=0)),
                ('horas_extra_nocturna', models.IntegerField(default=0)),
                ('horas_extra_diurna_dominical', models.IntegerField(default=0)),
                ('horas_extra_nocturna_dominical', models.IntegerField(default=0)),
                ('total_horas_extras', models.DecimalField(decimal_places=2, max_digits=10)),
                ('auxilio_transporte', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('descuento_salud', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descuento_pension', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nominas.usuario')),
            ],
        ),
    ]
