# Generated by Django 3.2.8 on 2024-10-22 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nominas', '0002_auto_20241022_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desprendible',
            name='descuento_pension',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='desprendible',
            name='descuento_salud',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='desprendible',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='desprendible',
            name='total_horas_extras',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
