# Generated by Django 3.2.8 on 2024-10-24 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nominas', '0004_alter_desprendible_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='desprendible',
            name='usuario',
        ),
        migrations.AddField(
            model_name='desprendible',
            name='usuario_cedula',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
