# Generated by Django 3.2.8 on 2024-10-30 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nominas', '0008_auto_20241026_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desprendible',
            name='usuario_cedula',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cedula',
            field=models.BigIntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='celular',
            field=models.BigIntegerField(),
        ),
    ]
